#!/bin/bash
# System-level setup for QLoRA training on AMD unified-memory APUs.
#
# Prefer invoking via 'sudo anvil train setup'.
#
# Three things tuned (each gated by a confirmation prompt):
#   1. Swap file grown to 64 GB           — absorbs CPU-side spillover when
#                                            the BIOS UMA carve-out leaves
#                                            system RAM tight.
#   2. ROCm env vars written to /etc/profile.d/ollama-anvil-training.sh
#         HSA_OVERRIDE_GFX_VERSION=11.0.0  (Strix Halo gfx1151 → gfx1100 ABI)
#         PYTORCH_ALLOC_CONF=expandable_segments:True
#         HSA_ENABLE_SDMA=0                (works around SDMA stalls on RDNA3.5)
#         HF_HUB_ENABLE_HF_TRANSFER=1      (faster checkpoint downloads)
#   3. amdgpu module options for larger GTT pool — lets the GPU back data
#      into system RAM dynamically instead of being capped by the static
#      UMA frame buffer.
#
# Must run with sudo (writes to /etc, /swapfile-anvil, /etc/modprobe.d).
# Re-running is safe: each step is idempotent.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "This script must run with sudo (it edits /etc and grows the swap file)."
    echo "Re-run as: sudo anvil train setup"
    exit 1
fi

REAL_USER="${SUDO_USER:-$USER}"
SWAP_TARGET_GB=64
SWAP_PATH="/swapfile-anvil"
ENV_FILE="/etc/profile.d/ollama-anvil-training.sh"
MOD_FILE="/etc/modprobe.d/amdgpu-anvil.conf"

confirm() {
    local prompt="$1"
    read -r -p "$prompt [y/N] " resp
    [[ "$resp" =~ ^[Yy]$ ]]
}

echo "ollama-anvil QLoRA system setup"
echo "================================"
echo

# --- 1. Swap ------------------------------------------------------------------
CURRENT_SWAP_KB=$(awk '/^SwapTotal:/ {print $2}' /proc/meminfo)
CURRENT_SWAP_GB=$((CURRENT_SWAP_KB / 1024 / 1024))
echo "Current swap: ${CURRENT_SWAP_GB} GB"

if [[ $CURRENT_SWAP_GB -lt $SWAP_TARGET_GB ]]; then
    if confirm "Grow swap to ${SWAP_TARGET_GB} GB at ${SWAP_PATH}?"; then
        if swapon --show=NAME --noheadings | grep -qx "$SWAP_PATH"; then
            swapoff "$SWAP_PATH"
        fi
        # fallocate'd files don't always work as swap on all FSes (e.g. btrfs),
        # so we run mkswap and verify.
        rm -f "$SWAP_PATH"
        if ! fallocate -l "${SWAP_TARGET_GB}G" "$SWAP_PATH" 2>/dev/null; then
            dd if=/dev/zero of="$SWAP_PATH" bs=1M count=$((SWAP_TARGET_GB * 1024)) status=progress
        fi
        chmod 600 "$SWAP_PATH"
        mkswap "$SWAP_PATH"
        swapon "$SWAP_PATH"

        if ! grep -q "^$SWAP_PATH " /etc/fstab; then
            echo "$SWAP_PATH none swap sw 0 0" >> /etc/fstab
        fi
        echo "Swap is now $(awk '/^SwapTotal:/ {print int($2/1024/1024)}' /proc/meminfo) GB"
    fi
else
    echo "Swap already >= ${SWAP_TARGET_GB} GB — skipping."
fi
echo

# --- 2. Environment variables -------------------------------------------------
echo "Writing ROCm + HF env vars to $ENV_FILE..."
cat > "$ENV_FILE" <<'EOF'
# ollama-anvil: environment for ROCm LoRA / QLoRA training.
# Generated by 'anvil train setup' — re-run that command to refresh.

# Strix Halo (gfx1151) and Phoenix (gfx1103) need this so HIP kernels
# compiled for gfx1100 (RX 7900 family) execute correctly. Harmless on
# real gfx1100 / gfx1101 / gfx1102 silicon.
export HSA_OVERRIDE_GFX_VERSION=11.0.0

# Reduce allocator fragmentation during long training runs.
# torch>=2.9 deprecated PYTORCH_HIP_ALLOC_CONF in favor of the unified
# PYTORCH_ALLOC_CONF. Setting both keeps older torch builds working too.
export PYTORCH_ALLOC_CONF=expandable_segments:True
export PYTORCH_HIP_ALLOC_CONF=expandable_segments:True

# SDMA on RDNA3+ APUs occasionally stalls during D2H copies; the blit
# path is slightly slower but reliable.
export HSA_ENABLE_SDMA=0

# Faster model downloads from the HF Hub (uses hf_transfer when available).
export HF_HUB_ENABLE_HF_TRANSFER=1

# Cap dataset cache so it doesn't compete with model staging on small RAM.
export HF_DATASETS_IN_MEMORY_MAX_SIZE=2147483648  # 2 GB
EOF
chmod 644 "$ENV_FILE"
echo "  -> sourced for all login shells of all users"
echo

# --- 3. amdgpu GTT pool size --------------------------------------------------
# GTT is the dynamic system-RAM region the kernel maps as GPU memory on
# top of the static VRAM. By default amdgpu caps GTT around half of system
# RAM, which is fine on discrete cards but hurts on UMA APUs where we
# *want* the GPU to spill into the rest of physical RAM.
echo "Writing $MOD_FILE..."
cat > "$MOD_FILE" <<'EOF'
# ollama-anvil: enlarge GTT so the GPU can dynamically use system RAM
# beyond the static UMA frame buffer. The kernel still respects per-app
# allocator limits; this only raises the ceiling.
options amdgpu gttsize=98304
options amdgpu vm_fragment_size=9
EOF
chmod 644 "$MOD_FILE"
echo "  -> takes effect after the next reboot (or 'sudo update-initramfs -u && reboot')"
echo

# --- 4. Permissions ----------------------------------------------------------
# render/video group is required to access /dev/kfd and /dev/dri/render*.
for grp in render video; do
    if getent group "$grp" >/dev/null && ! id -nG "$REAL_USER" | grep -qw "$grp"; then
        usermod -aG "$grp" "$REAL_USER"
        echo "Added $REAL_USER to $grp group (log out and back in to apply)."
    fi
done

cat <<EOF

Setup complete. To finish:
  1. Reboot (or at minimum log out and back in) so the env vars and amdgpu
     module options take effect.
  2. Confirm with: anvil train diagnose
  3. Install the training stack into your venv:
       source .venv/bin/activate
       anvil train install
  4. Run the reference trainer:
       anvil train run --model meta-llama/Llama-3.1-8B

If you have BIOS access on this machine, also consider lowering the UMA
frame buffer to ~32 GB. That frees ~64 GB back to the OS as system RAM
and is the cleanest fix for the CPU-side OOM. See docs/qlora-training.md
for the BIOS-side guidance.
EOF
